# Generated by Django 3.1.1 on 2020-09-27 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurent_name', models.CharField(max_length=50, unique=True)),
                ('restaurent_address', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=6)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=5)),
                ('image', models.ImageField(max_length=2000, upload_to='')),
                ('delivery_time', models.IntegerField(default=60)),
                ('offer', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('Bakery', 'Bakery'), ('Bengali', 'Bengali'), ('Biryani', 'Biryani'), ('Cafe', 'Cafe'), ('Chaat', 'Chaat'), ('Chinese', 'Chinese'), ('Desserts', 'Desserts'), ('Fast Food', 'Fast Food'), ('French', 'French'), ('Ice Cream', 'Ice Cream'), ('Indian', 'Indian'), ('Italian', 'Italian'), ('Kebabs', 'Kebabs'), ('Lucknowi', 'Lucknowi'), ('Maharashtrian', 'Maharashtrian'), ('Mexican', 'Mexican'), ('Mughlai', 'Mughlai'), ('North Indian', 'North Indian'), ('Pastas', 'Pastas'), ('Pizzas', 'Pizzas'), ('Punjabi', 'Punjabi'), ('Rajasthani', 'Rajasthani'), ('Snacks', 'Snacks'), ('South Indian', 'South Indian'), ('Street Food', 'Street Food'), ('Sweets', 'Sweets'), ('Tandoor', 'Tandoor'), ('Thalis', 'Thalis')], max_length=25)),
                ('cuisine', models.CharField(choices=[('North Indian', 'North Indian'), ('South Indian', 'South Indian'), ('Chinese', 'Chinese'), ('Italian', 'Italian'), ('French', 'French'), ('Punjabi', 'Punjabi')], max_length=25)),
                ('restaurent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.restaurent')),
            ],
        ),
    ]
