# Generated by Django 3.1.1 on 2020-09-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_food_restaurent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.BooleanField(default=False),
        ),
    ]
