# Generated by Django 3.1.1 on 2020-10-01 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200929_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='restaurent',
        ),
    ]
