# Generated by Django 3.1.1 on 2020-10-03 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_food_restaurent'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='rest_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurent_food', to='accounts.restaurent'),
        ),
        migrations.AddField(
            model_name='restaurent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
