# Generated by Django 3.1.1 on 2020-10-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_food_restaurent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cuisine',
            field=models.CharField(choices=[('North Indian', 'North Indian'), ('South Indian', 'South Indian'), ('Chinese', 'Chinese'), ('Italian', 'Italian'), ('sweets', 'sweets'), ('Punjabi', 'Punjabi'), ('non-veg', 'non-veg')], max_length=25),
        ),
    ]
