# Generated by Django 3.1.1 on 2020-10-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201003_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cooking_time',
            field=models.IntegerField(blank=True, default=60),
        ),
        migrations.AddField(
            model_name='user',
            name='restaurent',
            field=models.BooleanField(default=False),
        ),
    ]
