# Generated by Django 3.1.1 on 2020-10-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201006_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='rating',
            field=models.CharField(default='5 1', max_length=20),
        ),
    ]
