# Generated by Django 3.1.1 on 2020-10-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201006_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurent',
            name='wallpaper',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to=''),
        ),
    ]
