# Generated by Django 3.1.1 on 2020-10-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_restaurent_wallpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurent',
            name='rating',
            field=models.CharField(default='5 1', max_length=30),
        ),
    ]
