# Generated by Django 3.1.1 on 2020-10-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_restaurent_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='offer',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
