# Generated by Django 3.1.1 on 2020-09-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200930_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='foods',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
