# Generated by Django 3.1.1 on 2020-10-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_food_restaurent'),
        ('cart', '0009_checkoutaddress_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='myorder',
            name='foods',
            field=models.ManyToManyField(to='accounts.Food'),
        ),
        migrations.AddField(
            model_name='myorder',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='myorder',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
