# Generated by Django 3.1.1 on 2020-10-02 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0010_auto_20201002_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='foods',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='myorder',
            name='quantity',
        ),
        migrations.AddField(
            model_name='myorder',
            name='order_items',
            field=models.ManyToManyField(to='cart.OrderItem'),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
