# Generated by Django 3.1.1 on 2020-10-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_checkoutaddress_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered_date',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ordered_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='MyOrder',
        ),
    ]
