# Generated by Django 3.1.1 on 2020-10-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_auto_20201007_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discounted_price',
            field=models.FloatField(default=0),
        ),
    ]
