# Generated by Django 3.1.1 on 2020-09-25 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0003_auto_20200925_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurent',
            old_name='r_address',
            new_name='restaurent_address',
        ),
        migrations.RenameField(
            model_name='restaurent',
            old_name='r_name',
            new_name='restaurent_name',
        ),
        migrations.RenameField(
            model_name='restaurent',
            old_name='zipcode',
            new_name='zip_code',
        ),
    ]
