# Generated by Django 3.1.1 on 2020-09-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0005_auto_20200925_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Restaurent')], default=1),
        ),
    ]
