# Generated by Django 3.1.1 on 2020-09-25 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0006_auto_20200925_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=5)),
                ('image', models.ImageField(max_length=2000, upload_to='')),
                ('offer', models.PositiveIntegerField(default=0)),
                ('category', models.IntegerField(choices=[(1, 'Bakery'), (2, 'Bengali'), (3, 'Biryani'), (4, 'Cafe'), (5, 'Chaat'), (6, 'Chinese'), (7, 'Desserts'), (8, 'Fast Food'), (9, 'French'), (10, 'Ice Cream'), (11, 'Indian'), (12, 'Italian'), (13, 'Kebabs'), (14, 'Lucknowi'), (15, 'Maharashtrian'), (16, 'Mexican'), (17, 'Mughlai'), (18, 'North Indian'), (19, 'Pastas'), (20, 'Pizzas'), (21, 'Punjabi'), (22, 'Rajasthani'), (23, 'Snacks'), (24, 'South Indian'), (25, 'Street Food'), (26, 'Sweets'), (27, 'Tandoor'), (28, 'Thalis')])),
                ('cuisine', models.IntegerField(choices=[(1, 'North Indian'), (2, 'South Indian'), (3, 'Chinese'), (4, 'Italian'), (5, 'French'), (6, 'Punjabi')])),
                ('restaurent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccounts.restaurent')),
            ],
        ),
    ]
