# Generated by Django 3.1.1 on 2020-09-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0006_auto_20200925_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
    ]
