# Generated by Django 3.1.1 on 2020-09-27 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0008_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='delivery_time',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='food',
            name='restaurent',
            field=models.ForeignKey(default='Avantika', on_delete=django.db.models.deletion.CASCADE, to='useraccounts.restaurent'),
        ),
    ]
