# Generated by Django 3.1.1 on 2020-09-27 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0009_auto_20200927_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='restaurent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='useraccounts.restaurent'),
        ),
    ]
