# Generated by Django 3.1.1 on 2020-10-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rate_count',
            field=models.IntegerField(choices=[(1, 'VERY BAD'), (2, 'BAD'), (3, 'GOOD'), (4, 'VERY GOOD'), (5, 'EXCELLENT')]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='review',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
